### ISSUE TITLE
Images directory should be rewritten as well

### ISSUE THREAD

**Issue by mattions** [dinoboff/github-tools#10]
Hi,

I tried to add an image with the directive
    .. image:: images/ball.png

The image is properly copied into the images directory in the docs/_build/html/images but the html has still coded the one with the underscore:
    <img alt="_images/ball.png" src="_images/ball.png" />

Also that bit should be fixed.

**Comment by mattions** [comment]
for the time being you can use this per oneliner to have your image showing up
      perl -i -pe 's/_images/images/g' *.html

**Comment by mattions** [comment]
this is mine conf.py

```
    html_static_path = ['_static', 'images']
```

**Comment by dinoboff** [comment]
The extension no more necessary. I will add ".nojekyll" file to the template.

**Comment by dinoboff** [comment]
fixed 0.2b2
