### ISSUE TITLE
sphinx "_images" directories not renamed to "images"

### ISSUE THREAD

**Issue by astraw** [dinoboff/github-tools#14]
Hi,

Using the matplotlib.sphinxext.plot_directive, you can include auto-generated plots in your Sphinx documentation. Unfortunately, these get generated in a "_images" directory and Jekyll won't show them.

Can you do some more sphinx extension foo to rename these directories? (I like what you've done with _source.)

**Comment by dinoboff** [comment]
The extesnion is no more necessary. The paster template just need a .nojekyll file:

http://github.com/blog/572-bypassing-jekyll-on-github-pages

**Comment by dinoboff** [comment]
fixed with 0.2b2
